name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Prepare tailwindcss
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build-tailwindcss

      - name: Build
        run: trunk build --release

      - name: Create 404.html
        run: cp ./dist/index.html ./dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: annil-web.mmf.moe
